#!/bin/bash
#SBATCH --qos highmem1
#SBATCH --account=iacc_jeirinlo
#SBATCH --partition highmem1

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 16

#SBATCH --output=log_shortstack_all_trimmed_ACAL

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules

module load bedtools2-2.27.1-gcc-8.2.0-bxmhnwb

pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################


source activate ShortStack4


ShortStack \
--genomefile /scratch/jeirinlo/jrodr979/Aplysia_trans_WGBS/AplCal3.0_genome/unplaced.scaf.fa \
--readfile /scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-02-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-21-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-09-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-06-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-07-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-06-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-05-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-04-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-19-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-01-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-14-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-01-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-04-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-12-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-08-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-10-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-16-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-03-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-02-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-22-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-15-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-05-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-20-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-18-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB443-03-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-17-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-23-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-11-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-13-trimmed.fastq.gz \
/scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/Trimmed_files/RSB441-24-trimmed.fastq.gz \
--knownRNAs /scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/20230306_nf-smrnaseq/mature.fa \
--outdir /scratch/jeirinlo/jrodr979/miRNA_aplysia_hypoxia/20230317_shortstack_annot/20230320_Trimmed_Files_alignments \
--threads 16 \
--dn_mirna