#!/bin/bash
#SBATCH --account=iacc_jeirinlo
#SBATCH --qos highmem1
#SBATCH --partition IB_44C_512G

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 16

#SBATCH --output=20240404_ACAL_log_FastQC

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules

module load bowtie-1.2-gcc-4.8.5-pwetvpc 

pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################

trimmed_files="/scratch/jeirinlo/jrodr979/sncRNA_ACAL/Trimmed_files"
genome="/scratch/jeirinlo/jrodr979/ACAL_meth/genome/unplaced.scaf.fna"
output="/scratch/jeirinlo/jrodr979/sncRNA_ACAL/20240404_Bowtie_mapping"
# Build bowtie index

#bowtie-build ${genome} ACAL_index

# Run alignments

for f in ${trimmed_files}/*.fastq 
do
STEM=$(basename "${f}" -trimmed.fastq)
bowtie \
-v 2 \
--best \
-m 50 \
-p $SLURM_CPUS_ON_NODE \
-S ACAL_index \
"${f}" > "${STEM}".sam
done

