#!/bin/bash
#SBATCH --qos highmem1
#SBATCH --account=iacc_jeirinlo
#SBATCH --partition IB_44C_512G

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 16

#SBATCH --output=log_BS_SNPer

##########################################################
# Setup envrionmental variable.
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE

module load samtools-1.15.1-gcc-8.2.0
module load perl-5.34.0-gcc-8.2.0-b5u622f
pwd; hostname; date

echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################


#samtools merge \
#ACAL_merged.bam \
#/scratch/jeirinlo/jrodr979/ACAL_meth/bam_files/*.sorted.bam

perl /home/jrodr979/Programs/BS-Snper-master/BS-Snper.pl \
ACAL_merged.bam \
--fa /scratch/jeirinlo/jrodr979/ACAL_meth/genome/unplaced.scaf.fna \
--output snp.candidate.out \
--methcg meth.cg \
--methchg meth.chg \
--methchh meth.chh \
--minhetfreq 0.1 \
--minhomfreq 0.85 \
--minquali 15 \
--mincover 10 \
--maxcover 1000 \
--minread2 2 \
--errorate 0.02 \
--mapvalue 20 \
>SNP.vcf 2>SNP.log


grep $'C\tG' SNP.vcf > CT-SNP.vcf
wc -l CT-SNP.vcf