#!/bin/bash
#SBATCH --account=iacc_jeirinlo
#SBATCH --qos highmem1
#SBATCH --partition highmem1

# Number of nodes
#SBATCH -N 1

# Number of tasks
#SBATCH -n 8

#SBATCH --output=20220901_Aplysia_log_FastQC

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules
module load jdk-11.0.1-gcc-8.2.0-ref6fpq
module load libfontenc-1.1.3-gcc-8.2.0-vmvzydg
module load fastqc-0.11.7-gcc-8.2.0-gia624n
module load miniconda3-4.5.11-gcc-8.2.0-oqs2mbg
pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"

##########################################################

FastQ_files="/scratch/jeirinlo/jrodr979/Aplysia_hypoxia/TagSeq/Raw_reads"
out_dir="/scratch/jeirinlo/jrodr979/Aplysia_hypoxia/TagSeq/20220901_FastQC_raw"

for f in ${FastQ_files}/*fq
do
fastqc --outdir=${out_dir} --threads 8  ${f}
done   


#generate multiQC report
cd ${out_dir}
source activate my_anaconda

multiqc .

conda deactivate

