---
title: "Aplysia_hypoxia_exp_20220328 (7 days @ 21C/with 6h pulses of <20% DO Batches #60 and #71)"
author: "Javier Rodriguez Casariego"
date: "4/20/2022"
output: html_document
---


```{r load libraries, include=FALSE}

library(lubridate)
library(gridExtra)
library(ggplot2)
library(data.table)
library(ggpubr)

```


# Read sensor data
```{r}
# load sensor data

sensor_trt <- read.csv("phenotype/data/DO_data/Aplysia_exp_20220328_trt.csv", header = T)
sensor_trt <- sensor_trt[, -1]

sensor_ctrl <- read.csv("phenotype/data/DO_data/Aplysia_exp_20220328_ctrl.csv", header = TRUE)
sensor_ctrl <- sensor_ctrl[,-1]


# convert to date time format
sensor_trt$Date.Time..GMT.04.00 <- mdy_hm(sensor_trt$Date.Time..GMT.04.00)
sensor_ctrl$Date.Time..GMT.04.00 <- mdy_hm(sensor_ctrl$Date.Time..GMT.04.00)

colnames(sensor_trt) <- c("date_time", "DO", "Temp")
colnames(sensor_ctrl) <- c("date_time", "DO", "Temp")

## Computer time was wrong at the time of starting the sensors. Sensors were initialized at 11 am, so I need to substract two hours
hrs <- 2*60*60

sensor_ctrl$date_time <- sensor_ctrl$date_time - hrs
sensor_trt$date_time <- sensor_trt$date_time - hrs
sensor_ctrl$time <- as.ITime(sensor_ctrl$date_time)
sensor_trt$time <- as.ITime(sensor_trt$date_time)
sensor_ctrl$date <-as.IDate(sensor_ctrl$date_time)
sensor_trt$date <-as.IDate(sensor_trt$date_time)

sensor_ctrl_agg <- sensor_ctrl[,2:4]
sensor_ctrl_mean <- aggregate(.~time, sensor_ctrl_agg, function(x) c(mean = mean(x), sd = sd(x)))
sensor_ctrl_mean$time <- as.POSIXct(sensor_ctrl_mean$time)

sensor_trt_agg <- sensor_trt[,2:4]
sensor_trt_mean <- aggregate(.~time, sensor_trt_agg, function(x) c(mean = mean(x), sd = sd(x)))
sensor_trt_mean$time <- as.POSIXct(sensor_trt_mean$time)
```

# Plot DO and temperature tracks
```{r plot time series}

p1 <- ggplot(sensor_trt, aes(x=date_time)) +
  
  geom_line( aes(y=Temp), size=0.5, color="blue") + 
  geom_line( aes(y=DO*2), size=0.5, color="black") +
  ggtitle("Hypoxia") +
  scale_x_datetime(name="Time") +
  scale_y_continuous(
    
    # Features of the first axis
    name = "Temp (°C)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*0.5, name="DO (mg/mL)")
  ) + 
  
  theme_bw() +

  theme(
    axis.title.y = element_text(size=11),
    axis.title.y.right = element_text(size=11)
  )  


p2 <- ggplot(sensor_ctrl, aes(x=date_time)) +
  
  geom_line( aes(y=Temp), size=0.5, color="blue") + 
  geom_line( aes(y=DO*2), size=0.5, color="black") +
  ggtitle("Control") +
  scale_x_datetime(name="Time") +
  scale_y_continuous(
    
    # Features of the first axis
    name = "Temp (°C)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*0.5, name="DO (mg/mL)")
  ) + 
  
  theme_bw() +
  theme(
    axis.title.y = element_text(size=11),
    axis.title.y.right = element_text(size=11)
  ) 

ggsave("phenotype/figures/DO_Temp_plots.png", plot = grid.arrange(p1, p2, ncol=1), width = 8, height = 3)

# Plot average 


p3 <-ggplot(sensor_trt_mean, aes(x=time, group = 1)) +
  geom_line( aes(y=Temp[,1]), size=0.5, color="black", linetype = 2) + 
  geom_ribbon(aes(y = Temp[,1], ymin = Temp[,1] - Temp[,2], ymax = Temp[,1] + Temp[,2]), alpha = 0.35) +
  geom_line( aes(y=DO[,1]*2), size=0.5, color="black") +
  geom_ribbon(aes(y = DO[,1]*2, ymin = DO[,1]*2 - DO[,2], ymax = DO[,1]*2 + DO[,2]), alpha = 0.35) +
  scale_x_datetime(date_breaks = "3 hour", date_labels = "%H:%M") +
  #scale_x_time(breaks = scales::breaks_width("4 hour"), date_labels = "%H:%M") +
  scale_y_continuous(
    
    # Features of the first axis
    name = "Temp (°C)",
    
    # Add a second axis and specify its features
    sec.axis = sec_axis(~.*0.5, name="DO (mg/mL)")
  ) + 
  
  theme_bw() +

  theme(
    axis.title.y = element_text(size=11),
    axis.title.y.right = element_text(size=11)
  )  

ggsave("phenotype/figures/DO_Temp_daily_average_plots.png", p3, width = 6, height = 3)

p3
```


