---
title: "Aplysia_hypoxia_reflexes_&_growth"
author: "Javier Rodriguez Casariego"
date: "`r Sys.Date()`"
output: html_document
---

```{r load libraries, include=FALSE}

library(devtools)
library(dygraphs)
library(xts)
library(gridExtra)
library(ggplot2)
library(dplyr)
library(patchwork) # To display 2 charts together install.packages("patchwork")
library(hrbrthemes) # install.packages("hrbrthemes")
library(vegan)
library(dplyr)
library(pairwiseAdonis) # install_github("pmartinezarbizu/pairwiseAdonis/pairwiseAdonis")
library(data.table)
library(janitor) # install.packages("janitor")
library(chron) # install.packages("chron")
library(ggpubr)
library(ggsignif) # install.packages("ggsignif")

```

# Growth
```{r plot growth per batch, fig.width = 4, fig.height = 3}

weight <- read.csv("phenotype/data/Growth/growth_data.csv")

weight$treatment <- as.factor(weight$treatment)
weight$sample <- as.factor(weight$sample)
weight$batch <- as.factor(weight$batch)
levels(weight$treatment) <- c("control", "hypoxia")
levels(weight$sample) <- c("Day 1", "Day 6")

p1 <- ggplot(weight[which(weight$batch=="60"),], aes(x=sample, y=weight.g., fill = treatment)) +
  geom_boxplot() +
  scale_x_discrete(limits=c("Day 1", "Day 6")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Total weight (g)") +
  theme_classic();p1

weight2 <- weight[which(weight$sample=="Day 1"),]
colnames(weight2)[6] <- "day_1" 
weight2$day_6 <- weight[which(weight$sample=="Day 6"), 6]
weight2$rate <- weight2$day_6/weight2$day_1


p2 <- ggplot(weight2, aes(x = treatment, y = rate, fill = batch)) +
  geom_boxplot() +
  scale_fill_brewer(palette="Greys", name = "cohort", labels = c("naive", "pre-exposed")) + 
  labs(x=NULL, y = "Growth rate (Final_Weight/Initial_Weight)") +
  theme_classic() + 
  stat_compare_means(aes(group = batch), label = "p.signif", hide.ns = T, show.legend = F, label.y = 1.3);p2


ggsave("phenotype/figures/growth_rate.pdf", p2, width = 4, height = 4)

```

Reflexes analyses
```{r plot reflexes, fig.width = 12, fig.height = 6}
# load behavioral data

reflex <- read.csv("phenotype/data/Reflex_data_experiment_20220328.csv", header = TRUE, )

TTR <- reflex[,c(1:6)] # Keep only Pre and Post Hypoxia and eliminate NAs
TWR <- reflex[,c(1:5,7:8,10)]

colnames(TTR) <- c("ID","treatment","batch", "cage", "sample","TTR")
colnames(TWR) <- c("ID","treatment","batch", "cage","sample","Li","Lc","duration")

#TTR

TTR$treatment <- as.factor(TTR$treatment)
TTR$sample <- as.factor(TTR$sample)
TTR$batch <- as.factor(TTR$batch)
levels(TTR$treatment) <- c("control", "hypoxia")
levels(TTR$sample)
levels(TTR$treatment)
levels(TTR$batch)

#replace failed for a large number
TTR$TTR <- as.numeric(gsub(">120", 120, TTR$TTR))

p1 <- ggplot(TTR[which(TTR$batch=="60"),], aes(x=sample, y=TTR, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Time to Right (s)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

p4 <- ggplot(TTR[which(TTR$batch=="71"),], aes(x=sample, y=TTR, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Time to Right (s)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

# TWR 

TWR$contraction <- TWR$Li-TWR$Lc
TWR <- TWR[, c(1:5,8:9)] # keep only duration and contraction
#replace failed for a large number
TWR$duration[is.na(TWR$duration)] <- 120
TWR$contraction[is.na(TWR$contraction)] <- 0
head(TWR)

TWR$treatment <- as.factor(TWR$treatment)
TWR$sample <- as.factor(TWR$sample)

levels(TWR$treatment) <- c("control", "hypoxia")

p2 <- ggplot(TWR[which(TTR$batch=="60"),], aes(x=sample, y=duration, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Duration TWR (s)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

p3 <- ggplot(TWR[which(TTR$batch=="60"),], aes(x=sample, y=contraction, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Amplitude TWR (cm)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

p5 <- ggplot(TWR[which(TTR$batch=="71"),], aes(x=sample, y=duration, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Duration TWR (s)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment, size = 10), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

p6 <- ggplot(TWR[which(TTR$batch=="71"),], aes(x=sample, y=contraction, fill = treatment)) +
  geom_boxplot(outlier.alpha = 0.2) +
  scale_x_discrete(limits=c("Day 2", "Day 3", "Day 4", "Day 5", "Day 6", "Day 7")) +
  scale_fill_discrete(name = "treatment", labels = c("control", "hypoxia")) +
  scale_fill_brewer(palette="Greys") + 
  labs(x=NULL, y = "Amplitude TWR (cm)") +
  theme_classic() +
  stat_compare_means(aes(group = treatment, size = 10), method = "wilcox.test",label = "p.signif", hide.ns = T, show.legend = F)

reflex_plot <- ggarrange(p1, p2, p3, p4, p5, p6, ncol=3, nrow=2, common.legend = TRUE, legend="right")

reflex_plot <- annotate_figure(reflex_plot, left = text_grob("Pre-exposed                                    Naïve", face = "bold", rot = 90, size = 14), bottom = text_grob("Days of repeated exposure to 6hr hypoxic pulses or control conditions", size = 12))

ggsave("phenotype/figures/reflex_plot.pdf", reflex_plot, width = 12, height = 6)

reflex_plot
```


# Confirm significance with PERMANOVA
```{r}
# PERMANOVA analyses 
# General differences

adonis2(TTR$TTR~treatment*sample*batch, data = TTR, method = "euclidean")

#Per batch
TTR60 <- TTR[which(TTR$batch==60),]
TTR71 <- TTR[which(TTR$batch==71),]
adonis2(TTR60$TTR~treatment*sample, data = TTR60, method = "euclidean")
adonis2(TTR71$TTR~treatment*sample, data = TTR71, method = "euclidean")

# Per batch and sample date for batch 60 that showed significant effects treatment:sample 
adonis2(TTR60[which(TTR60$sample=="Day 2"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 2"),], na.rm =T, method = "euclidean")
adonis2(TTR60[which(TTR60$sample=="Day 3"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 3"),], na.rm =T, method = "euclidean")
adonis2(TTR60[which(TTR60$sample=="Day 4"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 4"),], na.rm =T, method = "euclidean")
adonis2(TTR60[which(TTR60$sample=="Day 5"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 5"),], na.rm =T, method = "euclidean")
adonis2(TTR60[which(TTR60$sample=="Day 6"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 6"),], na.rm =T, method = "euclidean")
adonis2(TTR60[which(TTR60$sample=="Day 7"),]$TTR~treatment, 
       data = TTR60[which(TTR60$sample=="Day 7"),], na.rm =T, method = "euclidean")

# TWR general
adonis2(TWR$duration~treatment*sample*batch, data = TWR, method = "euclidean", by= NULL)
adonis2(TWR$duration~treatment*sample, data = TWR, strata = TWR$batch, method = "euclidean")

adonis2(TWR$contraction~treatment*sample*batch, data = TWR, method = "euclidean", by = NULL)
adonis2(TWR$contraction~treatment*sample, 
        data = TWR, strata = TWR$batch, method = "euclidean")

#Per batch
TWR60 <- TWR[which(TTR$batch==60),]
TWR71 <- TWR[which(TTR$batch==71),]

adonis2(TWR60$duration~treatment*sample, data = TWR60, method = "euclidean")
adonis2(TWR71$duration~treatment*sample, data = TWR71, method = "euclidean")

adonis2(TWR60$contraction~treatment*sample, data = TWR60, method = "euclidean")
adonis2(TWR71$contraction~treatment*sample, data = TWR71, method = "euclidean")

## Per batch and sample date for batch 60 that showed significant effects treatment:sample for both duration and contraction 
adonis2(TWR60[which(TWR60$sample=="Day 2"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 2"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 3"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 3"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 4"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 4"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 5"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 5"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 6"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 6"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 7"),]$duration~treatment, 
       data = TWR60[which(TWR60$sample=="Day 7"),], method = "euclidean")

adonis2(TWR60[which(TWR60$sample=="Day 2"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 2"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 3"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 3"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 4"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 4"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 5"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 5"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 6"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 6"),], method = "euclidean")
adonis2(TWR60[which(TWR60$sample=="Day 7"),]$contraction~treatment, 
       data = TWR60[which(TWR60$sample=="Day 7"),], method = "euclidean")

## Per batch and sample date for batch 71 that showed significant effects treatment:sample for duration only
adonis2(TWR71[which(TWR71$sample=="Day 2"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 2"),], method = "euclidean")
adonis2(TWR71[which(TWR71$sample=="Day 3"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 3"),], method = "euclidean")
adonis2(TWR71[which(TWR71$sample=="Day 4"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 4"),], method = "euclidean")
adonis2(TWR71[which(TWR71$sample=="Day 5"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 5"),], method = "euclidean")
adonis2(TWR71[which(TWR71$sample=="Day 6"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 6"),], method = "euclidean")
adonis2(TWR71[which(TWR71$sample=="Day 7"),]$duration~treatment, 
       data = TWR71[which(TWR71$sample=="Day 7"),], method = "euclidean")

```
