---
title: "ACAL_alignment_compare"
author: "Javier Rodriguez Casariego"
date: "3/08/2023"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

load libraries
```{r}
library(ggplot2)
```


read in data
```{r}
data <- read.csv("20230309_AS_compare.csv", stringsAsFactors = F)

```

Analyis for Alignment parameters with bowtie2/clip10 trim


convert to long format
```{r}
STACKED_data <- tidyr::gather(data, "Context", "percent", 10:13)
STACKED_data <- STACKED_data[,c(1:2, 19:20)]

#make context labels more clear
STACKED_data$Context <- gsub("percent_aligned","% mapping", STACKED_data$Context)
STACKED_data$Context <- gsub("percent_c", "% mC", STACKED_data$Context)
STACKED_data$Context <- gsub("_meth", "", STACKED_data$Context)
```

dot plot
```{r}
ggplot(STACKED_data, aes(AS, percent, color = File)) + geom_point(alpha = 0.5) + facet_wrap(~Context, scale = "free") + theme_bw() + theme(legend.position="none") 

```


box plots
```{r}
#PE data
ggplot(STACKED_data, aes(AS, percent, group = AS)) + geom_boxplot() + facet_wrap(~Context, scale = "free") + theme_bw()+ xlab("Alignment score threshold") + ylab("percent")

jpeg("20230309_ASxmCandMapping.jpg", width = 7, height = 6, units = "in", res = 300)
ggplot(STACKED_data, aes(AS, percent, group = AS)) + geom_boxplot() + facet_wrap(~Context, scale = "free") + theme_bw() + xlab("Alignment score threshold") + ylab("percent")
dev.off()
```

