#!/bin/bash
#SBATCH --account=iacc_jeirinlo
#SBATCH --qos highmem1
#SBATCH --partition highmem1
#SBATCH -N 1
#SBATCH -n 4
#SBATCH --job-name=tag-seq_align
#SBATCH --output=log_STAR_BLau_align_20220915

###########################################################################################################
# Code Modified from Ben Laufer (blaufer@ucdavis.edu) and https://www.lexogen.com/quantseq-data-analysis/ #
###########################################################################################################

##########################################################
# Setup envrionmental variable. 
##########################################################
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE
. $MODULESHOME/../global/profile.modules
MEM=$(expr ${SLURM_MEM_PER_CPU} / 1024)

module load star-2.7.9a
module load samtools-1.9-gcc-8.2.0-o53igvd
module load fastqc-0.11.7-gcc-8.2.0-gia624n
module load miniconda3-4.5.11-gcc-8.2.0-oqs2mbg

pwd; hostname; date
 
echo "Running program on $SLURM_CPUS_ON_NODE CPU cores"
echo "Allocated memory: " $MEM
##########################################################


######################
# Set Up Environment #
######################

source activate bbmap_env

cd /scratch/jeirinlo/jrodr979/Aplysia_hypoxia/TagSeq/20220909_Trim_STAR_alignment_2

directory=${PWD}/
sample=`sed "${SLURM_ARRAY_TASK_ID}q;d" task_samples.txt`
rawpath=${directory}raw_sequences/
mappath=${directory}${sample}
fastq=${rawpath}${sample}.fq
trim=${sample}_trimmed.fastq
BAM=${sample}_Aligned.sortedByCoord.out.bam
genomeDir=${directory}data/AplCal3.0/star_100

###################
# Run Information #
###################

end=`date +%s`
runtime=$((end-start))
echo $runtime


########
# Trim #
########
# polyA file workaround: https://www.biostars.org/p/236515/
# Added stats for multiQC: https://multiqc.info/docs/#bbmap

mkdir ${mappath}
cd ${mappath}

call="bbduk.sh \
in=${fastq} \
out=${trim} \
ref=${directory}data/truseq_rna.fa.gz \
literal=AAAAAAAAAAAAAAAAAA \
k=13 \
ktrim=r \
useshortkmers=t \
mink=5 \
qtrim=r \
trimq=10 \
minlength=20 \
stats=${sample}_stats"

echo $call
eval $call

#############
# QC Report #
#############
# adjust threads

mkdir -p QC_trim

call="fastqc \
--outdir QC_trim \
--format fastq \
--threads 4 \
${trim}"

echo $call
eval $call


#########
# Align #
#########
# adjust threads and genome directory
# Use zcat command for fastq.gz https://www.biostars.org/p/243683/
# Use qauntMode to get GeneCounts for R https://www.biostars.org/p/218995/

call="STAR \
--runThreadN 4 \
--genomeDir ${genomeDir} \
--readFilesIn ${trim} \
--readFilesCommand cat \
--outFilterType BySJout \
--outFilterMultimapNmax 20 \
--alignSJoverhangMin 8 \
--alignSJDBoverhangMin 1 \
--outFilterMismatchNmax 999 
--outFilterMismatchNoverLmax 0.1 \
--outFilterScoreMinOverLread 0.3 \
--outFilterMatchNminOverLread 0.3 \
--outReadsUnmapped Fastx \
--alignIntronMin 20 \
--alignIntronMax 1000000 \
--alignMatesGapMax 1000000 \
--outSAMattributes NH HI NM MD \
--outSAMtype BAM SortedByCoordinate \
--outFileNamePrefix ${sample}_ \
--quantMode GeneCounts"


echo $call
eval $call

#########
# Index #
#########
# Indexed bam files are necessary for many visualization and downstream analysis tools

call="samtools \
index \
${BAM}"

echo $call
eval $call


###################
# Run Information #
###################

end=`date +%s`
runtime=$((end-start))
echo $runtime